In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [2]:
tenant = pd.read_csv("Rental_History_08_23_23.csv")
tenant.shape

(647, 57)

In [3]:
#Data set basics
pd.set_option('display.max_columns', None)
pd.set_option("display.max_rows", None)
tenant.drop(index=tenant.index[0], axis=0, inplace=True)
tenant.head()

,Respondent ID,Collector ID,Start Date,End Date,IP Address,Email Address,First Name,Last Name,Custom Data 1,What is your age?,What is the highest level of education you have completed?,What is your annual income?,What is your occupation?,Unnamed: 13,What was your credit score when you moved in?,What is your total amount of your monthly rent?,What was the total security deposit for your current rental?,How did you pay for the security deposit?,Unnamed: 18,What type of living space do you currently rent?,What is the zip code of your current rental?,Please indicate your gender:,Unnamed: 22,What is your relationship status?,How many people were on your rental application?,What are the ages of all tenants? (excluding yourself),What is the total salary of all tenants (including yourself)?,How many pets do you have?,What type of pet(s) do you have? (If applicable),Unnamed: 29,Unnamed: 30,Unnamed: 31,Do you smoke?,How many times per month have you needed to contact your current landlord/manager?,What types of issues have caused you to contact your landlord/manager?,Unnamed: 35,Unnamed: 36,Unnamed: 37,"Generally, these interactions with the landlord have been:",Have you ever been convicted of a crime?,Have you been evicted from a previous rental?,Have you been late or missed a rent payment in the last 3 years?,How many times? (If applicable),What was the total amount of your security deposit of your last rental? (Enter N/A if you have not rented before),How much of your total security deposit did you receive back at the end of your stay? (Enter N/A if you have not rented before),How long did you stay at your last rental?,Your contact info: (please include phone/email to qualify for free rent prize),Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52,Unnamed: 53,Unnamed: 54,Unnamed: 55,Are you interested in being contacted for services in the future?
1,1.143965e+11,426684317.0,08/23/2023 10:29:26 PM,08/23/2023 10:35:12 PM,35.150.247.128,NaN,NaN,NaN,NaN,56,Bachelor's degree,1479,Disabled/Unable to Work,NaN,300-579,1180,1750,Other (please specify),Got agency help,Apartment/Condo,30067,Female,NaN,Single,Only me,56,1180,0,NaN,NaN,NaN,Other,No,Never,NaN,NaN,NaN,Air unit went out,Very positive,No,No,No,NaN,NaN,NaN,3+ years,Mia Allison,NaN,NaN,NaN,NaN,NaN,NaN,NaN,miaallison1966@gmail.com,4043387706,Yes - please contact me for future offerings
2,1.143965e+11,426684317.0,08/23/2023 10:28:03 PM,08/23/2023 10:31:16 PM,72.178.131.198,NaN,NaN,NaN,NaN,35,Graduated from high school or GED,36000,Janitor,NaN,300-579,550,200,Other (please specify),Paid in full,Apartment/Condo,76710,Female,NaN,Married/partner,2,32,3600,3+,Dog,NaN,NaN,NaN,No,1-2 times,NaN,Small maintenance requests (loose door handles...,"Large maintenance requests (leaks, broken refr...",NaN,Very negative,Yes - misdemeanor,No,No,1,200,0,3+ years,Lara Garcia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,pnlgarcia1316@gmail.com,2544207562,No - I am only interested in the offer of free...
3,1.143965e+11,426684317.0,08/23/2023 09:58:41 PM,08/23/2023 10:05:57 PM,172.56.168.253,NaN,NaN,NaN,NaN,32,Some college,2100,Healthcare Management,Caregiver,300-579,2800,2800,Split among all tenants,NaN,Single Family Home,95628,Female,NaN,Single,3+,"40,18,16,12,13,6",6800,1,Dog,NaN,NaN,NaN,No,1-2 times,NaN,Small maintenance requests (loose door handles...,NaN,NaN,Very positive,No,No,No,NaN,Na,Na,< 1 year,Jasmine Leblanc,NaN,NaN,NaN,NaN,NaN,NaN,NaN,jasmine_mariah@ymail.com,9168896818,Yes - please contact me for future offerings
4,1.143965e+11,426684317.0,08/23/2023 09:52:53 PM,08/23/2023 10:00:30 PM,172.58.204.94,NaN,NaN,NaN,NaN,70,Graduated from high school or GED,"18,000",Retired,NaN,580-669,1500,800,Had money in savings,NaN,Duplex,04101,Female,NaN,Divorced,2,61,Not sure,1,Dog,NaN,NaN,NaN,No,<1 time,NaN,NaN,"Large maintenance requests (leaks, broken refr...",NaN,Positive,No,No,No,NaN,Dont remember,I have lived here 22 years,2 years,Virginia Bachelder,NaN,NaN,NaN,NaN,NaN,NaN,NaN,bacheldercindy222@gmail.com,2076180953,No - I am only interested in the offer of free...
5,1.143965e+11,426684317.0,08/23/2023 09:27:37 PM,08/23/2023 09:33:47 PM,68.185.230.16,NaN,NaN,NaN,NaN,51,Some college,"45,000",Counselor,NaN,580-669,625,625,Had money in savings,NaN,Single Family Home,70454,Female,NaN,Married/partner,3+,"51, 45, 18","90,000",0,NaN,NaN,NaN,Other,No,<1 time,NaN,Small maintenance requests (loose door handles...,NaN,NaN,Positive,No,No,No,NaN,725,725,3+ years,Meka Bowers,NaN,NaN,NaN,NaN,NaN,NaN,NaN,momathomas6@gmail.com,9856346410,Yes - please contact me for future offerings

In [4]:
tenant.columns

Index(['Respondent ID', 'Collector ID', 'Start Date', 'End Date', 'IP Address',
       'Email Address', 'First Name', 'Last Name', 'Custom Data 1',
       'What is your age?',
       'What is the highest level of education you have completed?',
       'What is your annual income?', 'What is your occupation?',
       'Unnamed: 13', 'What was your credit score when you moved in?',
       'What is your total amount of your monthly rent?',
       'What was the total security deposit for your current rental?',
       'How did you pay for the security deposit?', 'Unnamed: 18',
       'What type of living space do you currently rent?',
       'What is the zip code of your current rental?',
       'Please indicate your gender:', 'Unnamed: 22',
       'What is your relationship status?',
       'How many people were on your rental application?',
       'What are the ages of all tenants? (excluding yourself)',
       'What is the total salary of all tenants (including yourself)?',
       'How many pets do you have?',
       'What type of pet(s) do you have? (If applicable)', 'Unnamed: 29',
       'Unnamed: 30', 'Unnamed: 31', 'Do you smoke?',
       'How many times per month have you needed to contact your current  landlord/manager?',
       'What types of issues have caused you to contact your landlord/manager?',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37',
       'Generally, these interactions with the landlord have been:',
       'Have you ever been convicted of a crime?',
       'Have you been evicted from a previous rental?',
       'Have you been late or missed a rent payment in the last 3 years?',
       'How many times? (If applicable)',
       'What was the total amount of your security deposit of your last rental? (Enter N/A if you have not rented before)',
       'How much of your total security deposit did you receive back at the end of your stay? (Enter N/A if you have not rented before)',
       'How long did you stay at your last rental?',
       'Your contact info: (please include phone/email to qualify for free rent prize)',
       'Unnamed: 47', 'Unnamed: 48', 'Unnamed: 49', 'Unnamed: 50',
       'Unnamed: 51', 'Unnamed: 52', 'Unnamed: 53', 'Unnamed: 54',
       'Unnamed: 55',
       'Are you interested in being contacted for services in the future?'],
      dtype='object')

In [5]:
#Initial data cleaning
#drop useless columns
columns = ['Respondent ID', 'Collector ID', 'Start Date', 'End Date', 'IP Address',
       'Email Address', 'First Name', 'Last Name', 'Custom Data 1', 'Unnamed: 47', 'Unnamed: 48', 'Unnamed: 49', 'Unnamed: 50',
       'Unnamed: 51', 'Unnamed: 52', 'Unnamed: 53',]
tenant.drop(columns, inplace=True, axis=1)

In [6]:
#renaming all columns
dict = {'What is your age?' : 'age',
       'What is the highest level of education you have completed?' : 'education',
       'What is your annual income?' : 'individual_income', 
       'What is your occupation?' : 'occupation',
       'Unnamed: 13' : 'occupation_other',
       'What was your credit score when you moved in?' : 'credit_score',
       'What is your total amount of your monthly rent?' : 'monthly_rent',
       'What was the total security deposit for your current rental?' : 'deposit_amount',
       'How did you pay for the security deposit?' : 'deposit_payment_method', 
       'Unnamed: 18' : 'deposit_payment_method_other',
       'What type of living space do you currently rent?' : 'type_residence',
       'What is the zip code of your current rental?' : 'zip_code',
       'Please indicate your gender:' : 'gender', 
       'Unnamed: 22' : 'gender_other',
       'What is your relationship status?' : 'relationship_status',
       'How many people were on your rental application?' : 'number_applicants',
       'What are the ages of all tenants? (excluding yourself)' : 'all_tenant_ages',
       'What is the total salary of all tenants (including yourself)?' : 'total_income',
       'How many pets do you have?' : 'number_of_pets', 
       'What type of pet(s) do you have? (If applicable)' : 'pet_dog', 
       'Unnamed: 29' : 'pet_cat', 
       'Unnamed: 30' : 'pet_reptile',
       'Unnamed: 31' : 'pet_other', 
       'Do you smoke?' : 'smoker',
       'How many times per month have you needed to contact your current  landlord/manager?' : 'landlord_contact_frequency',
       'What types of issues have caused you to contact your landlord/manager?' : 'landlord_contact_admin', 
       'Unnamed: 35' : 'landlord_contact_small_maintenance',
       'Unnamed: 36' : 'landlord_contact_large_maintenance',
       'Unnamed: 37' : 'landlord_contact_other',
       'Generally, these interactions with the landlord have been:' : 'landlord_interaction_rating',
       'Have you ever been convicted of a crime?' : 'convicted_crime',
       'Have you been evicted from a previous rental?' : 'eviction_history',
       'Have you been late or missed a rent payment in the last 3 years?' : 'payment_history',
       'How many times? (If applicable)' : 'payment_history_frequency',
       'What was the total amount of your security deposit of your last rental? (Enter N/A if you have not rented before)' : 'previous_security_deposit_amount',
       'How much of your total security deposit did you receive back at the end of your stay? (Enter N/A if you have not rented before)' : 'previous_security_depsoit_returned',
       'How long did you stay at your last rental?' : 'previous_rental_stay_length_years',
       'Your contact info: (please include phone/email to qualify for free rent prize)' : 'tenant_name',
       'Unnamed: 54': 'tenant_phone',
       'Unnamed: 55': 'tenant_email',
       'Are you interested in being contacted for services in the future?' : 'future_contact'}

tenant.rename(columns=dict,
          inplace=True)

In [7]:
tenant.columns

Index(['age', 'education', 'individual_income', 'occupation',
       'occupation_other', 'credit_score', 'monthly_rent', 'deposit_amount',
       'deposit_payment_method', 'deposit_payment_method_other',
       'type_residence', 'zip_code', 'gender', 'gender_other',
       'relationship_status', 'number_applicants', 'all_tenant_ages',
       'total_income', 'number_of_pets', 'pet_dog', 'pet_cat', 'pet_reptile',
       'pet_other', 'smoker', 'landlord_contact_frequency',
       'landlord_contact_admin', 'landlord_contact_small_maintenance',
       'landlord_contact_large_maintenance', 'landlord_contact_other',
       'landlord_interaction_rating', 'convicted_crime', 'eviction_history',
       'payment_history', 'payment_history_frequency',
       'previous_security_deposit_amount',
       'previous_security_depsoit_returned',
       'previous_rental_stay_length_years', 'tenant_name', 'tenant_phone',
       'tenant_email', 'future_contact'],
      dtype='object')

In [53]:
tenant['future_contact'].value_counts()

Yes - please contact me for future offerings           395
No - I am only interested in the offer of free rent    239
Name: future_contact, dtype: int64

In [8]:
#Data cleaning. Columns that need work: individual_income, occuptaion, monthly_rent, deposit_amount, deposit_payment_method,
# gender, number_applicants, all_tenant_ages, total_income, number_of_pets, type_pet, landlord_contact_frequency, landlord_contact_type, 
#  payment_history, 

#columns that don't need cleaning: age, credit_score, education, type_residence, zip_code, relationship_status, smoker, landlord_interaction_rating
# convicted_crime, eviction_history, payment_history_frequency, previous_security_deposit_amount, previous_rental_stay_length_years
#

#Drop useless rows
values_to_drop = ['Idk', 'Prefer not to say', 'Too little', 'Retired', 'Student', 'On social security ', 'Less than 10,000',
                  '999999', '40.000.00', '11.800.00', 'Below 10.000', 'Under 25,000.00']
tenant = tenant.loc[~tenant['individual_income'].isin(values_to_drop)]

#clean characters
clear_income_characters = [',', ';', '$', ' ', 'Under', 'Below',]
for char in clear_income_characters:
    tenant['individual_income'] = tenant['individual_income'].str.replace(char, '')

#Change to zero. Second thought, I am removing these because they don't provide useful data.
# change_to_zero = ['Retired', 'Student', 'Onsocialsecurity']

# for char in change_to_zero:
#     tenant['individual_income'] = tenant['individual_income'].str.replace(char, '0')
# tenant['individual_income'].value_counts()

C:\Users\rdpet\AppData\Local\Temp\ipykernel_19212\614499998.py:13: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  tenant['individual_income'] = tenant['individual_income'].str.replace(char, '')

In [9]:
def clean_income(value):
    if 'k' in value:
        value = value.replace('k', '000')
        
    if 'K' in value:
        value = value.replace('K', '000')
        
    if 'thasand' in value:
        value = value.replace('thasand', '000')

    if "\'" in value:
        value = value.replace(value, '28000')

#typo in entry
    if  value == '560000':
        value = value.replace(value, '56000')
        
#     if value == '27000-30000':
#         value = value.replace(value, '28500')
        
#     if value == '30000-40000':
#         value = value.replace(value, '35000')
        
#     if value == '25000-30000':
#         value = value.replace(value, '27500')
        
    if '-' in value:
        split_parts = value.split('-')
        value = value.replace(value, split_parts[1])
#         value = value.replace(value, '27500')

    return value

# # Apply the cleaning function to the 'individual_income' column
tenant['individual_income'] = tenant['individual_income'].apply(clean_income)

In [10]:
tenant['individual_income'] = tenant['individual_income'].astype(float)
tenant['individual_income'].dtypes

dtype('float64')

In [11]:
def income_math(value):
#     if value.isnumeric():
#         value = value*1000
#     if '-' in value:
#         parts = value.split('-')
#         avg = (int(parts[0]) + int(parts[1])) / 2
#         value = int(parts[0])
#     if value.isnumeric():
#         value = int(value)
        if value < 125:
            value *= 1000
        elif 125 <= value <= 2000:
            value *= 12
        return value

tenant['individual_income'] = tenant['individual_income'].apply(income_math)
tenant['individual_income'].value_counts()

# individual_income column finished

25000.0     35
30000.0     32
40000.0     29
20000.0     24
50000.0     23
10000.0     20
12000.0     20
32000.0     17
35000.0     15
45000.0     15
15000.0     15
24000.0     14
75000.0     12
11000.0     12
0.0         11
13000.0     10
26000.0      9
60000.0      9
55000.0      8
19000.0      8
36000.0      8
38000.0      8
23000.0      8
27000.0      8
47000.0      7
43000.0      7
34000.0      6
42000.0      6
70000.0      6
100000.0     6
29000.0      6
14000.0      6
28000.0      6
48000.0      5
22000.0      5
41000.0      5
65000.0      5
33000.0      5
9000.0       5
17000.0      4
58000.0      4
51000.0      4
37000.0      4
18000.0      4
16000.0      4
52000.0      4
21000.0      4
14400.0      3
5000.0       3
80000.0      3
39000.0      3
54000.0      3
10968.0      3
49000.0      3
6000.0       2
96000.0      2
2500.0       2
31000.0      2
22800.0      2
74000.0      2
16500.0      2
68000.0      2
13300.0      2
46000.0      2
9800.0       2
16800.0      2
8000.0       2
73000.0      2
7000.0       2
120000.0     2
23500.0      2
68500.0      1
20040.0      1
37600.0      1
25009.0      1
69000.0      1
22621.0      1
18480.0      1
12600.0      1
29099.0      1
18141.0      1
105000.0     1
18670.0      1
48200.0      1
17748.0      1
20400.0      1
13540.0      1
67000.0      1
28765.0      1
33480.0      1
10986.0      1
56000.0      1
43215.0      1
19200.0      1
110500.0     1
17988.0      1
4800.0       1
49600.0      1
44000.0      1
83000.0      1
14500.0      1
11208.0      1
22960.0      1
22102.0      1
15250.0      1
27500.0      1
121000.0     1
57000.0      1
37907.0      1
18204.0      1
3000.0       1
30563.0      1
86000.0      1
11352.0      1
30100.0      1
10900.0      1
18500.0      1
17774.0      1
41600.0      1
84460.0      1
113000.0     1
200000.0     1
19550.0      1
8076.0       1
17820.0      1
78000.0      1
7200.0       1
24336.0      1
59000.0      1
37200.0      1
23760.0      1
87000.0      1
15500.0      1
102712.0     1
35500.0      1
2100.0       1
11440.0      1
49454.0      1
79000.0      1
18312.0      1
38755.0      1
37440.0      1
19368.0      1
14868.0      1
45800.0      1
8900.0       1
13248.0      1
76600.0      1
13080.0      1
16200.0      1
42869.0      1
5640.0       1
39500.0      1
11500.0      1
19908.0      1
26500.0      1
11134.0      1
13260.0      1
36500.0      1
9600.0       1
53000.0      1
62000.0      1
Name: individual_income, dtype: int64

In [12]:
tenant['individual_income'].describe()

count       634.000000
mean      33150.151420
std       22249.287926
min           0.000000
25%       17785.500000
50%       29049.500000
75%       43000.000000
max      200000.000000
Name: individual_income, dtype: float64

In [13]:
#combining and formatting occupation columns

tenant.loc[tenant['occupation_other'].notnull(), 'occupation'] = tenant['occupation_other']
tenant['occupation'] = tenant['occupation'].str.rstrip()
  
occupation_replacement_values = {
"Other":"Other",
"Customer Service":"Customer Service",
"Retired":"Retired",
"Disabled/Unable to Work":"Disabled/Unable to Work",
"Food Service":"Food Service",
"Homemaker":"Homemaker",
"Social Security":"Social Security",
"Sales":"Sales",
"Teacher":"Teacher",
"Nurse":"Nurse",
"Admin Assistant":"Admin Assistant",
"Business Managment":"Business Managment",
"Cashier/Clerk":"Cashier/Clerk",
"Disabled":"Disabled",
"IT":"IT",
"Insurance":"Insurance",
"Delivery Driver":"Delivery Driver",
"Finance":"Finance",
"Uber/Lyft":"Uber/Lyft",
"Construction":"Construction",
"Healthcare Management":"Healthcare Management",
"Student":"Student",
"Logistics":"Logistics",
"Childcare":"Childcare",
"Counselor":"Counselor",
"Social Worker":"Social Worker",
"Accounting":"Accounting",
"Janitor":"Janitor",
"Marketing":"Marketing",
"Lawyer":"Lawyer",
"Manufacturing":"Manufacturing",
"Software Developer":"Software Developer",
"Police officer/Security Guard":"Police officer/Security Guard",
"Director of Hotel Revenue":"Hospitality",
"Unemployed health reason":"Disabled",
"Wireless retail professional":"Sales",
"Teachers aide":"Borrowed money",
"Currently unemployed but looking for work":"Unemployed",
"Stay at home mom":"Homemaker",
"Other please specify":"Other",
"Property management":"Property Management",
"Bartender":"Bartender",
"Call Center Representative":"Customer Service",
"Engineer":"Engineer",
"Beauty":"Beauty",
"Laboratory Chemist":"Chemist",
"Dental Hygienist":"Dentistry",
"Paralegal":"Paralegal",
"Heathcare Mangement":"Heathcare Mangement",
"Realtor":"Realtor",
"Student teacher":"Student TA",
"Nail Technician":"Beauty",
"Phlebotomist":"Nurse",
"Executive":"Management",
"Overnight stocker":"Cashier/Clerk",
"Nutrition Coach":"Nutrition Coach",
"Handyman":"Handyman",
"Community Outreach Worker":"Social Worker",
"Pharmacy technician":"Pharmacy Tech",
"Loan closer":"Finance",
"Pet sitter":"Admin Assistant",
"Cna":"Nurse",
"Entertainment":"Entertainment",
"Management/Hospitality":"Hospitality",
"Bus driver":"Uber/Lyft",
"electronic cleaner":"Janitor",
"Body man tech":"Other",
"Program Manager":"Management",
"Housekeeper":"Housekeeper",
"Bio-pharma research":"Student Research",
"Stadhehand":"Entertainment",
"Behavioral Tech":"Nurse",
"Retired/self-employed vocalist":"Retired",
"Landscaping": 'Landscaping',    
'Retired': 'Retired',
'Disabled': 'Disabled',
'Retired': 'Retired',
'Underwriter': 'Finance',
'(Receive my fathers pension)': 'Social Security',
'Administrative Assistant 1': 'Admin Assistant',
'I\'m on disability': 'Disabled',                     
'Claims Examiner': 'Insurance',
'Caregiver': 'Nurse',
'Home provider': 'Homemaker',
'Self employed healthcare management': 'Heathcare Mangement',
'Personal attendant': 'Nurse',
'Retired/Disabled': 'Disabled',
'Disable': 'Disabled',
'School bus driver': 'Uber/Lyft',
'retired': 'Retired',
'Seasonal tax preparer': 'Finance',
'Plant manager for medical equipment manufacturer': 'Manufacturing',
'Homemaker': 'Homemaker',
'Housewife': 'Homemaker',
'Home Maker': 'Homemaker',
'Realtor': 'Realtor',
'Child care': 'Childcare',
'insurance': 'Insurance',
'Behavior therapist': 'Counselor',
'Social Worker': 'Social Worker',
'EBay seller landscaper': 'Landscaping',
'Private Tutor': 'Teacher',
'Marketing': 'Marketing',
'Retired paralegal': 'Paralegal',
'Ss survivors': 'Social Security',
'Substitute teacher': 'Teacher',
'School Bus driver': 'Uber/Lyft',
'Medical assistant': 'Nurse',
'Secretary': 'Admin Assistant',
'Interpreter': 'Customer Service',
'Makeup Artist': 'Beauty',
'Postal worker': 'Logistics',
'CAll center representative': 'Customer Service',
'Travel Agent': 'Customer Service',
'Can\'t work': 'Disabled',
'Disability': 'Disabled',
'I clean the grocery store': 'Janitor',
'Dental hygienist': 'Dental Hygienist',
'Seafood clerk': 'Cashier/Clerk',
'Logistics': 'Logistics',
'Stay at home parent': 'Homemaker',
'Childcare': 'Childcare',
'AmeriCorps member': 'Social Security',
'Security guard': 'Police officer/Security Guard',
'Part time parts driver': 'Logistics',
'Disabled': 'Disabled',
'Handy man': 'Construction',
'Disabled unable to 3': 'Disabled',
'Food stamp Case Worker': 'Social Worker',
'Courier': 'Logistics'
                        }

tenant['occupation'] = tenant['occupation'].replace(occupation_replacement_values)

characters_to_remove = ['1', '3', '(', ')', "'", ',']

# Clearing the specified characters from the column
for char in characters_to_remove:
    tenant['occupation'] = tenant['occupation'].str.replace(char, '')
    



# tenant['occupation'] = tenant['occupation'].astype(str)

tenant['occupation'].value_counts()

C:\Users\rdpet\AppData\Local\Temp\ipykernel_19212\1774177691.py:145: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  tenant['occupation'] = tenant['occupation'].str.replace(char, '')

Other                            118
Customer Service                  81
Retired                           59
Disabled/Unable to Work           49
Food Service                      36
Social Security                   23
Homemaker                         22
Nurse                             19
Sales                             19
Teacher                           17
Admin Assistant                   15
Business Managment                14
Cashier/Clerk                     13
Disabled                          12
Finance                            9
IT                                 9
Insurance                          8
Uber/Lyft                          8
Delivery Driver                    8
Counselor                          7
Construction                       7
Healthcare Management              7
Childcare                          7
Logistics                          7
Social Worker                      7
Student                            5
Accounting                         5
Janitor                            5
Marketing                          4
Lawyer                             3
Manufacturing                      3
Police officer/Security Guard      2
Software Developer                 2
Entertainment                      2
Hospitality                        2
Beauty                             2
Management                         2
Dental Hygienist                   1
Handyman                           1
Paralegal                          1
Bartender                          1
Heathcare Mangement                1
Realtor                            1
Engineer                           1
Student Research                   1
Property Management                1
Unemployed                         1
Borrowed money                     1
Student TA                         1
Chemist                            1
Pharmacy Tech                      1
Nutrition Coach                    1
Landscaping                        1
Name: occupation, dtype: int64

In [14]:
# combined_cols = ['occupation_other', 'deposit_payment_method_other', 'landlord_contact_small_maintenance',
#        'landlord_contact_large_maintenance', 'landlord_contact_other', ]
# tenant.drop(combined_cols, inplace=True)
tenant.loc[tenant['deposit_payment_method'] == 'Other (please specify)', 'deposit_payment_method'] = tenant['deposit_payment_method_other']

tenant['deposit_payment_method'].value_counts()

Had money in savings                                                          314
Borrowed money                                                                169
No deposit                                                                     24
Split among all tenants                                                        18
Bank account                                                                    2
Paid cash                                                                       2
Tax refund                                                                      2
Cash                                                                            2
no deposit required                                                             1
Payments                                                                        1
A  charities                                                                    1
Got agency help                                                                 1
taxes                                                                           1
Family helped                                                                   1
No security deposit. I own mobile home and pay for rent on the land             1
Saved                                                                           1
There was no deposit.                                                           1
Did work                                                                        1
Housing voucher                                                                 1
Paid 100 per month for first 5 months                                           1
Used my full paycheck                                                           1
Used deposit from previous apt                                                  1
Had to put it together                                                          1
Aetna better health program                                                     1
Jetty                                                                           1
Paid cash that i saved                                                          1
Saved up                                                                        1
Worked extra hours                                                              1
Split in three payments                                                         1
Saved it                                                                        1
Split every month                                                               1
Section eight housing                                                           1
Over time                                                                       1
No deposit                                                                      1
Paycheck                                                                        1
401k                                                                            1
No security deposit                                                             1
Sold my house                                                                   1
Don’t remember since it was 12 years ago when we first moved here               1
Had money saved and had to borrow from a family member                          1
Income tax refund                                                               1
Used pay check                                                                  1
Got help from a government program                                              1
paid in payments                                                                1
Not applicable                                                                  1
Didn't have to pay that                                                         1
Worked it off                                                                   1
Haven't                                                                         1
Help from the state                                                             1
Assistance program                                                              1
Used Rhino                                                                      1
Pay every month $50                                                             1
Worked hard on lyft                                                             1
State aid                                                                       1
Equity                                                                          1
My son and his girlfriend paid it                                               1
Agency                                                                          1
I lived here for 14 years                                                       1
Loan                                                                            1
Paid alittle each month                                                         1
Paid out of paycheck                                                            1
Worked extra hours to save the money                                            1
Assistance from charities                                                       1
Dad                                                                             1
husband paid                                                                    1
Split into 2 payments                                                           1
I was working then                                                              1
Had to save and disability                                                      1
Still owe deposit                                                               1
An agency paid it.                                                              1
Added to monthly rent                                                           1
Urban League                                                                    1
Jetty                                                                           1
Paid directly from paycheck                                                     1
With my tax money                                                               1
Paid monthly with the rent                                                      1
Made two payments                                                               1
Money Order                                                                     1
So much each month til paid                                                     1
Half and half in 2 weeks                                                        1
Social Service agency                                                           1
Paid in installments                                                            1
Credit card                                                                     1
Credit card                                                                     1
Family residential                                                              1
Government agency                                                               1
Son paid the deposit                                                            1
Special program                                                                 1
Paid in full                                                                    1
Augusta Housing helped me                                                       1
Assist from tribal reservation                                                  1
Used fathers pension                                                            1
Income                                                                          1
Credit                                                                          1
Paid all at once when I moved in                                                1
Housing program paid the deposit                                                1
Na                                                                              1
Most paid by help from govt agency                                              1
a grant                                                                         1
Checking account                                                                1
Social Security payment                                                         1
Loan from church                                                                1
Refund check                                                                    1
Salvation Army                                                                  1
Held from proceeds of sale                                                      1
None                                                                            1
It was paid with the money from my last rentals deposit that was returned.      1
Gift                                                                            1
I joined the lease later, no request for security deposit                       1
Name: deposit_payment_method, dtype: int64

In [17]:
#combining and formatting deposit columns
tenant.loc[tenant['deposit_payment_method'] == 'Other (please specify)', 'deposit_payment_method'] = tenant['deposit_payment_method_other']

deposit_payment_method_replacement_values = {
"Cash":"Had money in savings",
"No deposit":"No deposit",
"Housing program paid the deposit":"Government Assistance",
"Equity":"Had money in savings",
"Assistance program":"Government Assistance",
"Used Rhino":"Third party software",
"Pay every month $50":"Paid over time",
"Worked hard on lyft":"Had money in savings",
"State aid":"Government Assistance",
"My son and his girlfriend paid it":"Borrowed money",
"Haven't":"No deposit",
"Agency":"Third party software",
"Section eight housing":"Government Assistance",
"Over time":"Paid over time",
"Used deposit from previous apt":"Had money in savings",
"Split every month":"Paid over time",
"Help from the state":"Government Assistance",
"Worked it off":"Traded labor",
"Saved":"Had money in savings",
"Didn't have to pay that":"No deposit",
"Not applicable":"No deposit",
"Bank account":"Had money in savings",
"paid in payments":"Paid over time",
"Got help from a government program":"Government Assistance",
"Used pay check":"Had money in savings",
"Income tax refund":"Had money in savings",
"Had money saved and had to borrow from a family member":"Borrowed money",
"Don’t remember since it was 12 years ago when we first moved here":"Had money in savings",
"Sold my house":"Had money in savings",
"No security deposit":"No deposit",
"401k":"Had money in savings",
"Paycheck":"Had money in savings",
"There was no deposit.":"No deposit",
"Did work":"Traded labor",
"No security deposit. I own mobile home and pay for rent on the land":"No deposit",
"Tax refund":"Had money in savings",
"Credit":"Borrowed money",
"Income":"Had money in savings",
"Used fathers pension":"Government Assistance",
"Assist from tribal reservation":"Government Assistance",
"Augusta Housing helped me":"Government Assistance",
"Loan":"Borrowed money",
"Special program":"Government Assistance",
"Jetty":"Third party software",
"Paid alittle each month":"Paid over time",
"I lived here for 14 years":"Had money in savings",
"Saved it":"Had money in savings",
"Split in three payments":"Paid over time",
"Worked extra hours":"Had money in savings",
"Paid cash":"Had money in savings",
"Paid all at once when I moved in":"Had money in savings",
"Saved up":"Had money in savings",
"Paid cash that i saved":"Had money in savings",
"Jetty":"Third party software",
"Aetna better health program":"Government Assistance",
"Had to put it together":"Had money in savings",
"Housing voucher":"Government Assistance",
"Used my full paycheck":"Had money in savings",
"Paid 100 per month for first 5 months":"Paid over time",
"Family helped":"Borrowed money",
"no deposit required":"No deposit",
"Payments":"Paid over time",
"A charities":"Government Assistance",
"taxes":"Had money in savings",
"I joined the lease later, no request for security deposit":"No deposit",
"Credit card":"Borrowed money",
"Salvation Army":"Government Assistance",
"Family residential":"No deposit",
"Government agency":"Government Assistance",
"Son paid the deposit":"Government Assistance",
"Gift":"Borrowed money",
"It was paid with the money from my last rentals deposit that was returned.":"Had money in savings",
"None":"No deposit",
"Held from proceeds of sale":"Had money in savings",
"a grant":"Government Assistance",
"Refund check":"Had money in savings",
"Loan from church":"Government Assistance",
"Social Security payment":"Had money in savings",
"Checking account":"Had money in savings",
"Assistance from charities":"Government Assistance",
"Most paid by help from govt agency":"Government Assistance",
"Na":"No deposit",
"A charities":"Government Assistance",
"Worked extra hours to save the money":"Traded labor",
"Response":"No deposit",
"Dad":"Government Assistance",
"With my tax money":"Had money in savings",
"Paid in full":"Had money in savings",
"Paid in installments":"Paid over time",
"Social Service agency":"Government Assistance",
"Half and half in 2 weeks":"Paid over time",
"So much each month til paid":"Paid over time",
"Money Order":"Borrowed money",
"Made two payments":"Paid over time",
"Paid monthly with the rent":"Paid over time",
"Paid directly from paycheck":"Had money in savings",
"husband paid":"Had money in savings",
"Urban League":"Government Assistance",
"Paid out of paycheck":"Had money in savings",
"Added to monthly rent":"Paid over time",
"An agency paid it.":"Third party software",
"Still owe deposit":"Paid over time",
"Had to save and disability":"Had money in savings",
"I was working then":"Had money in savings",
"Got agency help":"Government Assistance",
"Split into 2 payments":"Paid over time",

    
"Government Assistance":"Government/Charity Assistance",
}
tenant['deposit_payment_method'] = tenant['deposit_payment_method'].str.rstrip()

tenant['deposit_payment_method'] = tenant['deposit_payment_method'].replace(deposit_payment_method_replacement_values)

for char in characters_to_remove:
    tenant['deposit_payment_method'] = tenant['deposit_payment_method'].str.replace('  ', ' ')

tenant['deposit_payment_method'].value_counts()

Had money in savings             354
Borrowed money                   178
No deposit                        36
Government/Charity Assistance     24
Split among all tenants           18
Paid over time                    16
Third party software               5
Traded labor                       3
Name: deposit_payment_method, dtype: int64

In [18]:
tenant.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 634 entries, 1 to 646
Data columns (total 41 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   age                                 634 non-null    object
 1   education                           634 non-null    object
 2   individual_income                   634 non-null    float64
 3   occupation                          634 non-null    object
 4   occupation_other                    105 non-null    object
 5   credit_score                        634 non-null    object
 6   monthly_rent                        634 non-null    object
 7   deposit_amount                      634 non-null    object
 8   deposit_payment_method              634 non-null    object
 9   deposit_payment_method_other        109 non-null    object
 10  type_residence                      634 non-null    object
 11  zip_code                            634 non-null    object
 12  gender                              633 non-null    object
 13  gender_other                        2 non-null      object
 14  relationship_status                 634 non-null    object
 15  number_applicants                   634 non-null    object
 16  all_tenant_ages                     560 non-null    object
 17  total_income                        617 non-null    object
 18  number_of_pets                      634 non-null    object
 19  pet_dog                             204 non-null    object
 20  pet_cat                             179 non-null    object
 21  pet_reptile                         15 non-null     object
 22  pet_other                           153 non-null    object
 23  smoker                              634 non-null    object
 24  landlord_contact_frequency          634 non-null    object
 25  landlord_contact_admin              112 non-null    object
 26  landlord_contact_small_maintenance  362 non-null    object
 27  landlord_contact_large_maintenance  222 non-null    object
 28  landlord_contact_other              122 non-null    object
 29  landlord_interaction_rating         634 non-null    object
 30  convicted_crime                     634 non-null    object
 31  eviction_history                    634 non-null    object
 32  payment_history                     634 non-null    object
 33  payment_history_frequency           363 non-null    object
 34  previous_security_deposit_amount    533 non-null    object
 35  previous_security_depsoit_returned  516 non-null    object
 36  previous_rental_stay_length_years   634 non-null    object
 37  tenant_name                         631 non-null    object
 38  tenant_phone                        629 non-null    object
 39  tenant_email                        614 non-null    object
 40  future_contact                      634 non-null    object
dtypes: float64(1), object(40)
memory usage: 224.2+ KB

In [30]:
tenant['type_residence'].value_counts()

Apartment/Condo       374
Single Family Home    168
Other                  33
Duplex                 31
Trailer Park           28
Name: type_residence, dtype: int64

In [ ]:
# tenants.loc[tenants.pet_dog == 0, 'dog'] = 'N/A'

# tenant.rename(columns={'pet_dog': 'type_pet'}, inplace=True)
# tenant.loc[tenant['number_of_pets'] == '3+', 'type_pet'] = tenant['type_pet'] + ', ' + tenant['pet_cat'] + ', ' + tenant['pet_reptile'] + ', ' + tenant['pet_other']
# # tenant.loc[tenant['number_of_pets'] == '2', 'type_pet'] = tenant['type_pet'] + ', ' + tenant['pet_cat'] + ', ' + tenant['pet_reptile'] + ', ' + tenant['pet_other']
# tenant.loc[tenant['type_pet'] == 'N/A', 'type_pet'] = tenant['pet_cat']
# tenant.loc[tenant['type_pet'] == 'N/A', 'type_pet'] = tenant['pet_reptile']
# tenant.loc[tenant['type_pet'] == 'N/A', 'type_pet'] = tenant['pet_other']
# tenant.loc[tenant['type_pet'].isnull(), 'type_pet'] = tenant['pet_cat']
# tenant.loc[tenant['type_pet'].isnull(), 'type_pet'] = tenant['pet_reptile']
# tenant.loc[tenant['type_pet'].isnull(), 'type_pet'] = tenant['pet_other']
# tenant.loc[tenant['type_pet'].isnull(), 'type_pet'] = 'N/A'
# tenant.loc[tenant['number_of_pets'] == 0, 'type_pet'] = 'N/A'


# tenant['type_pet'].value_counts()

In [29]:
# tenant.loc[tenant['landlord_contact_admin'].isnull(), 'landlord_contact_admin'] = tenant['landlord_contact_small_maintenance']
# tenant.loc[tenant['landlord_contact_admin'].isnull(), 'landlord_contact_admin'] = tenant['landlord_contact_large_maintenance']
# tenant.loc[tenant['landlord_contact_admin'].isnull(), 'landlord_contact_admin'] = tenant['landlord_contact_other']

# tenant.rename(columns={'landlord_contact_admin': 'landlord_contact_type'}, inplace=True)
# tenant['landlord_contact_type'].value_counts()